### PR TITLE
Issue #424: Fix local-run.sh scripts so they can be executed from outside ci/<...> directory

### LINKED ISSUE #424: Some `local-run.sh` scripts cannot be executed from outside `ci/<...>` directory
```
$ ./ci/tox/local-run.sh 
./ci/tox/local-run.sh: line 5: ../local-run-commons.sh: No such file or directory
```

There's already even a `cd` to the right directory inside these scripts... it's just the sourcing of `local-run-commons.sh` that's wrong

### PR DESCRIPTION
**Pull request by amalota**
closes #424

### CODE REVIEW

File: ci/deb-ppa-upload/local-run.sh [hunk 1]
```diff
@@ -2,11 +2,10 @@
 
 set -e -o pipefail -u
 
-source ../local-run-commons.sh deb-ppa-upload
-check_env gpg-ssh.env
+source ci/local-run-commons.sh deb-ppa-upload
```
Comment (PawelLipski) [inline ci/deb-ppa-upload/local-run.sh]:
```suggestion
source "$(git rev-parse --show-toplevel)"/ci/local-run-commons.sh deb-ppa-upload
```
as below?

Comment (PawelLipski) [reply ci/deb-ppa-upload/local-run.sh]: Then it can be run from anywhere in the repo

File: ci/nixpkgs-build/local-run.sh [hunk 2]
```diff
@@ -2,10 +2,9 @@
 
 set -e -o pipefail -u
 
-cd "$(git rev-parse --show-toplevel)"/ci/nixpkgs-build/
-
-source ../local-run-commons.sh nixpkgs-build
+source ci/local-run-commons.sh nixpkgs-build
```
Comment (PawelLipski) [inline ci/nixpkgs-build/local-run.sh]: Ditto here and in next file

File: ci/checks/ensure-shell-scripts-pass-shellcheck.sh [hunk 3]
```diff
@@ -2,4 +2,4 @@
 
 set -e -o pipefail -u
 
-git ls-files '*.sh' | xargs shellcheck --check-sourced --exclude=SC2090,SC2125 --severity=warning --shell=bash
+git ls-files '*.sh' | xargs shellcheck --check-sourced --exclude=SC2090,SC2125,SC1090 --severity=warning --shell=bash
```
Comment (PawelLipski) [inline ci/checks/ensure-shell-scripts-pass-shellcheck.sh:5]: Right, good point

**Review by PawelLipski — APPROVED** [review]
