### PR TITLE
Dry-run deploy to Homebrew: No available formula with the name "git-machete"

### LINKED ISSUE #823: Dry-run deploy to Homebrew: `No available formula with the name "git-machete"`
See [this CI build](https://app.circleci.com/pipelines/github/VirtusLab/git-machete/3155/workflows/938e763f-43ef-48cd-91d5-da837bc88fb9/jobs/16514):

```
+ brew bump-formula-pr --write-only --force --no-browse --verbose --url https://test.pypi.org/packages/source/g/git-machete/git-machete-3.15.3.tar.gz --sha256 65937618bf86f11ede73aa95cb4ecec27e57c0f9802b7fc2c0fd5b19ccf96cd8 git-machete
Warning: bump-formula-pr is a developer command, so Homebrew's
developer mode has been automatically turned on.
To turn developer mode off, run:
  brew developer off

Error: No available formula with the name "git-machete".

Exited with code exit status 1
```

### PR DESCRIPTION
**Pull request by amalota**

### CODE REVIEW

File: ci/homebrew/ci-deploy.sh [hunk 1]
```diff
@@ -3,6 +3,7 @@
 set -e -o pipefail -u -x
 
 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" < /dev/null
+(echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/circleci/.bash_profile
```
Comment (PawelLipski) [inline ci/homebrew/ci-deploy.sh:7]: Hmmm what's the effect of **not** including this line? is it also sth related to 4.0.0 release of Homebrew? 🤔

Comment (amalota) [reply ci/homebrew/ci-deploy.sh:7]: @PawelLipski No it's not, it's related to the lines 1418-1435 from https://app.circleci.com/pipelines/github/VirtusLab/git-machete/3148/workflows/cc6b52ba-d2e0-49cc-a0d2-bd41e383b4a9/jobs/16464

Comment (PawelLipski) [reply ci/homebrew/ci-deploy.sh:7]: Okay... pls include a comment in code that mentions that it's needed to avoid `Warning: /home/linuxbrew/.linuxbrew/bin is not in your PATH`

File: ci/homebrew/ci-deploy.sh [hunk 2]
```diff
@@ -24,6 +26,9 @@ git config --global user.name "Git Machete Bot"
 
 # Relying on HOMEBREW_GITHUB_API_TOKEN, provided by the CI
 # See https://docs.brew.sh/Manpage -> Ctrl+F HOMEBREW_GITHUB_API_TOKEN
+
+# We need to run `brew tap homebrew/core` manually since it is no longer done by default when installing `brew`
```
Comment (PawelLipski) [inline ci/homebrew/ci-deploy.sh]:
```suggestion
# We need to run `brew tap homebrew/core` manually because since Homebrew 4.0.0 it is no longer done by default when installing `brew`; see https://brew.sh/2023/02/16/homebrew-4.0.0/
```

**Review by PawelLipski — APPROVED** [review]
