### PR TITLE
Issue #396: (Option #3) Use root user in the container, non-root locally

### LINKED ISSUE #427: Unneeded files end up in Debian package
From the output of `./local-run.sh` in `ci/deb-ppa-upload`:

```
+ tar tvf ../python3-git-machete_3.7.2~20.04.tar.gz
drwxrwxr-x 0/0               0 2022-02-10 12:21 git-machete/
-rw-r--r-- 0/0             127 2022-02-02 19:29 git-machete/.dockerignore
drwxr-xr-x 0/0               0 2021-11-27 22:33 git-machete/.mypy_cache/
drwxr-xr-x 0/0               0 2022-02-07 12:50 git-machete/.mypy_cache/3.10/
-rw-r--r-- 0/0               2 2022-02-07 12:50 git-machete/.mypy_cache/3.10/@plugins_snapshot.json
-rw-r--r-- 0/0          111685 2022-02-05 15:45 git-machete/.mypy_cache/3.10/_ast.data.json
-rw-r--r-- 0/0            1530 2022-02-07 12:50 git-machete/.mypy_cache/3.10/_ast.meta.json

......... tons of mypy cache files ...............

-rw-r--r-- 0/0            1596 2022-02-05 17:08 git-machete/.mypy_cache/3.9/urllib/response.meta.json
-rw-r--r-- 0/0           21568 2022-02-05 15:51 git-machete/.mypy_cache/3.9/warnings.data.json
-rw-r--r-- 0/0            1556 2022-02-05 17:08 git-machete/.mypy_cache/3.9/warnings.meta.json
-rw-r--r-- 0/0             189 2021-08-05 12:55 git-machete/.mypy_cache/CACHEDIR.TAG
-rw-r--r-- 0/0             120 2022-02-05 15:50 git-machete/.remarkrc.yml
-rw-r--r-- 0/0              31 2022-02-05 15:50 git-machete/.remarkrc_master.yml
-rw-r--r-- 0/0             126 2020-04-24 21:34 git-machete/MANIFEST.in
-rw-r--r-- 0/0            8652 2022-02-10 11:54 git-machete/README.md
drwxr-xr-x 0/0               0 2022-02-10 12:21 git-machete/debian/
-rw-r--r-- 0/0           13600 2022-02-10 12:21 git-machete/debian/changelog
-rw-r--r-- 0/0               3 2020-04-24 21:34 git-machete/debian/compat
-rw-r--r-- 0/0             425 2020-04-24 21:34 git-machete/debian/control
-rw-r--r-- 0/0            1075 2022-02-10 12:21 git-machete/debian/copyright
-rwxr-xr-x 0/0             125 2020-04-24 21:34 git-machete/debian/rules
drwxr-xr-x 0/0               0 2022-02-07 18:08 git-machete/debian/source/
-rw-r--r-- 0/0             749 2022-02-07 18:08 git-machete/debian/source/options
-rw-r--r-- 0/0             638 2021-11-25 13:48 git-machete/git-machete
drwxr-xr-x 0/0               0 2022-02-10 12:21 git-machete/git_machete/
-rw-r--r-- 0/0              22 2022-02-09 17:04 git-machete/git_machete/__init__.py
-rw-r--r-- 0/0           37136 2022-02-09 17:04 git-machete/git_machete/cli.py
-rw-r--r-- 0/0          123588 2022-02-09 17:04 git-machete/git_machete/client.py
-rw-r--r-- 0/0            1017 2022-02-02 19:47 git-machete/git_machete/constants.py
-rw-r--r-- 0/0           50348 2022-02-09 17:04 git-machete/git_machete/docs.py
-rw-r--r-- 0/0             855 2021-11-25 13:49 git-machete/git_machete/exceptions.py
-rw-r--r-- 0/0           49601 2022-02-07 18:08 git-machete/git_machete/git_operations.py
-rw-r--r-- 0/0           11646 2021-11-27 23:41 git-machete/git_machete/github.py
-rw-r--r-- 0/0            2865 2021-11-25 13:48 git-machete/git_machete/options.py
-rw-r--r-- 0/0            8696 2022-02-02 19:47 git-machete/git_machete/utils.py
-rw-r--r-- 0/0             193 2022-02-07 18:08 git-machete/requirements.txt
-rw-r--r-- 0/0            1255 2021-10-08 08:28 git-machete/setup.py
drwxr-xr-x 0/0               0 2022-02-10 09:33 git-machete/test-results/
-rw-r--r-- 0/0            6115 2022-02-10 09:33 git-machete/test-results/py38.xml
```

mypy cache, remark config, test results, .dockerignore - all should be added to `debian/source/options`

### PR DESCRIPTION
**Pull request by amalota**
closes https://github.com/VirtusLab/git-machete/issues/396

### CODE REVIEW

File: ci/tox/Dockerfile [hunk 1]
```diff
@@ -29,9 +29,27 @@ ENV PYTHON_VERSION=${python_version}
 ENV PYTHON=python${python_version}
 RUN apk add --no-cache gcc musl-dev # both packages are required to install mypy
 
+FROM base AS CIRCLE_CI
 RUN $PYTHON -m pip install tox
 ENV PATH=$PATH:/root/.local/bin/
```
Comment (PawelLipski) [inline ci/tox/Dockerfile:34]: Nit: is this still needed? does `pip` install stuff in `~/.local/bin` even when `--user` mode is NOT active? 🤔

File: ci/tox/local-run.sh [hunk 2]
```diff
@@ -10,5 +10,7 @@ check_var GIT_VERSION
 check_var PYTHON_VERSION
 
 set -x
-docker-compose build --build-arg user_id="$(id -u)" --build-arg group_id="$(id -g)" tox
-docker-compose run tox
+export TARGET=LOCAL
+export MOUNT_POINT=home/ci-user
+COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build --build-arg user_id="$(id -u)" --build-arg group_id="$(id -g)" tox
```
Comment (PawelLipski) [inline ci/tox/local-run.sh]: Wow so both env vars are needed to activate `target` feature in docker-compose? 😯

File: ci/tox/Dockerfile (hunk 1 above)
Comment (amalota) [reply ci/tox/Dockerfile:34]: Yeah, it crashes without it:
```
Installing git-machete script to /root/.local/bin

Installed /root/.local/lib/python3.10/site-packages/git_machete-3.7.2-py3.10.egg
Processing dependencies for git-machete==3.7.2
Finished processing dependencies for git-machete==3.7.2
+ git machete --version
git: 'machete' is not a git command. See 'git --help'.
```

Comment (amalota) [reply ci/tox/Dockerfile:34]: https://app.circleci.com/pipelines/github/VirtusLab/git-machete/1493/workflows/496f166b-54af-41cb-b9ee-2615fc80b2d4/jobs/6037

File: ci/tox/local-run.sh (hunk 2 above)
Comment (PawelLipski) [reply ci/tox/local-run.sh]: Awww okay, `DOCKER_BUILDKIT` is needed for multi-stage build in Dockerfile, and `COMPOSE_DOCKER_CLI_BUILD` just tells `docker-compose` to use `docker` CLI rather than some default builder, which wouldn't support multi-stage builds 🤯

Comment (amalota) [reply ci/tox/local-run.sh]: It actually is not needed, i forgot to push the code without it

Comment (amalota) [reply ci/tox/local-run.sh]: only:
```
export TARGET=LOCAL
export MOUNT_POINT=home/ci-user
```
is needed

Comment (amalota) [reply ci/tox/local-run.sh]: circleci has right settings by default to make it work

Comment (amalota) [reply ci/tox/local-run.sh]: and as it turns out locally docker also has right settings so there is no need for it

File: ci/rpm/Dockerfile [hunk 3]
```diff
@@ -1,17 +1,25 @@
-FROM fedora:31
+FROM fedora:31 as base
```
Comment (PawelLipski) [inline ci/rpm/Dockerfile]: You can bump to 35 while you're here

File: ci/rpm/Dockerfile [hunk 4]
```diff
@@ -1,17 +1,25 @@
...
 ARG user_id
 ARG group_id
 RUN set -x \
     && [ ${user_id:-0} -ne 0 ] \
     && [ ${group_id:-0} -ne 0 ] \
-    && groupadd -g ${group_id} ci-user \
-    && useradd -l -u ${user_id} -g ci-user ci-user \
-    && install -d -m 0755 -o ci-user -g ci-user /home/ci-user
+    # sometimes the given `group_id` is already taken and `addgroup` raises an error, so let's check its existence first
+    && (getent group $group_id || addgroup --gid=${group_id} ci-user) \
```
Comment (PawelLipski) [inline ci/rpm/Dockerfile]: Whoops

```
Step 13/18 : RUN set -x     && [ ${user_id:-0} -ne 0 ]     && [ ${group_id:-0} -ne 0 ]     && (getent group $group_id || addgroup --gid=${group_id} ci-user)     && useradd -l -u ${user_id} -g $group_id ci-user     && install -d -m 0755 -o ci-user -g $group_id /home/ci-user
 ---> Running in 740b6eef02a2
+ set -x
+ '[' 1000 -ne 0 ']'
+ '[' 1000 -ne 0 ']'
+ getent group 1000
+ addgroup --gid=1000 ci-user
/bin/bash: addgroup: command not found
```

Comment (PawelLipski) [reply ci/rpm/Dockerfile]: The entire change here is probably not needed, can stay as it was

Comment (amalota) [reply ci/rpm/Dockerfile]: Well, i got the error that the group exists and i cannot create it and that's why the change

Comment (amalota) [reply ci/rpm/Dockerfile]: `------                                                                                                                                                                                                                                                                                                                  
 > [local 1/4] RUN set -x     && [ 501 -ne 0 ]     && [ 20 -ne 0 ]     && groupadd -g 20 ci-user     && useradd -l -u 501 -g ci-user ci-user     && install -d -m 0755 -o ci-user -g ci-user /home/ci-user:                                                                                                             
#8 0.299 + set -x                                                                                                                                                                                                                                                                                                       
#8 0.300 + '[' 501 -ne 0 ']'
#8 0.300 + '[' 20 -ne 0 ']'
#8 0.300 + groupadd -g 20 ci-user
#8 0.301 groupadd: GID '20' already exists
`

Comment (amalota) [reply ci/rpm/Dockerfile]: How is that even possible that we get different results, docker is supposed to negate that

Comment (PawelLipski) [reply ci/rpm/Dockerfile]: Hmmm but I executed the commands the current commit (`95469471792513492476448b1a37157c41654d74`), while you've apparently executed sth else (with `groupadd` instead of `addgroup`)

Comment (amalota) [reply ci/rpm/Dockerfile]: Well, i just executed it for the mentioned commit and it works:
` => CACHED [local 1/4] RUN set -x     && [ 501 -ne 0 ]     && [ 20 -ne 0 ]     && (getent group 20 || addgroup --gid=20 ci-user)     && useradd -l -u 501 -g 20 ci-user     && install -d -m 0755 -o ci-user -g 20 /home/ci-user `

Comment (amalota) [reply ci/rpm/Dockerfile]: Are you sure you executed it for the `rpm`? nothing else comes to my mind

Comment (amalota) [reply ci/rpm/Dockerfile]: Sth is wrong, your message should start with: `[local 1/4] RUN set`
but it starts with: `Step 13/18 : RUN set`. Can you run it again, this time from the newest commit: [7d83000](https://github.com/VirtusLab/git-machete/pull/422/commits/7d8300008edcba23b751df37fc76aca0c62513f4)

Comment (PawelLipski) [reply ci/rpm/Dockerfile]: Oh, I see where the problem lies... our environments still do differ slightly:

In your case, host GID is 20, which happens to correspond to a group already existing in `fedora:35`, so `addgroup` is NOT executed. 

In my case, host GID is 1000, which does NOT correspond to  group already existing in `fedora:35`, so `addgroup` is attempted but fails, since such executable does NOT exist on fedora:

```
$ docker run fedora:35 groupadd --help
Usage: groupadd [options] GROUP

Options:
.....
```

but:

```
docker run fedora:35 addgroup --help
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "addgroup": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 
```

Comment (PawelLipski) [reply ci/rpm/Dockerfile]: Override both `build_arg`s to 1000 and see what happens

Comment (amalota) [reply ci/rpm/Dockerfile]: Alright, i see, in this case i'll change it to the `groupadd`

File: ci/deb-ppa-upload/docker-compose.yml [hunk 5]
```diff
@@ -5,12 +5,13 @@ services:
...
       context: build-context
       dockerfile: ../Dockerfile # relative to build-context
+      target: ${TARGET:-CIRCLE_CI}
       args:
         - user_id=${USER_ID:-0}
         - group_id=${GROUP_ID:-0}
     volumes:
       # Host path is relative to current directory, not build-context
-      - ./../..:/home/ci-user/git-machete
+      - ./../..:/${MOUNT_POINT:-root}/git-machete
```
Comment (PawelLipski) [inline ci/deb-ppa-upload/docker-compose.yml]: Uber-nitpick: I'd make the leading `/` a part of the mount point path as well:
```suggestion
      - ./../..:${MOUNT_POINT:-/root}/git-machete
```

Comment (PawelLipski) [reply ci/deb-ppa-upload/docker-compose.yml]: To be reflected in other files on this PR as well as in #425

File: ci/deb-ppa-upload/Dockerfile [hunk 6]
```diff
@@ -1,20 +1,35 @@
-FROM ubuntu:20.04
+FROM ubuntu:20.04 as base
 SHELL ["/bin/bash", "-e", "-o", "pipefail", "-u", "-x", "-c"]
 
 # See https://github.com/phusion/baseimage-docker/issues/58 for why DEBIAN_FRONTEND=noninteractive is needed.
 RUN apt-get update \
     && DEBIAN_FRONTEND=noninteractive apt-get install -y debhelper devscripts fakeroot dh-python gawk python3-all python3-paramiko python3-setuptools \
     && rm -rfv /var/lib/apt/lists/*
 
+FROM base AS CIRCLE_CI
```
Comment (PawelLipski) [inline ci/deb-ppa-upload/Dockerfile]: Another nit: so far I've rather seen Dockerfile stages being named in lowercase... `CIRCLE_CI` looks as is it were an env var

File: ci/deb-ppa-upload/Dockerfile [hunk 7]
```diff
@@ -1,20 +1,35 @@
...
+COPY gpg-sign.sh /root/
+RUN chmod +x ~/gpg-sign.sh
+
+COPY release-notes-to-changelog.awk /root/
+COPY entrypoint.sh /root/
+RUN chmod +x /root/entrypoint.sh
+CMD ["/root/entrypoint.sh"]
+WORKDIR /root/git-machete
+
+FROM base AS LOCAL
```
Comment (PawelLipski) [inline ci/deb-ppa-upload/Dockerfile]: ....or here `LOCAL` looks like a Dockerfile keyword (which it's not)

File: ci/rpm/Dockerfile (hunk 4 above)
Comment (PawelLipski) [reply ci/rpm/Dockerfile]: Okay! works

File: ci/deb-ppa-upload/local-run.sh [hunk 8]
```diff
@@ -9,6 +9,8 @@ cd "$(git rev-parse --show-toplevel)"/ci/deb-ppa-upload/
 
 
 set -x
+export TARGET=LOCAL
+export MOUNT_POINT=home/ci-user
```
Comment (PawelLipski) [inline ci/deb-ppa-upload/local-run.sh]: While you're here... pls fix #427, literally just adding stuff to Debian-ignore file

Comment (amalota) [reply ci/deb-ppa-upload/local-run.sh]: done

File: debian/source/options [hunk 9]
```diff
@@ -31,4 +31,8 @@ tar-ignore = .stestr.conf
 tar-ignore = *.swp
 tar-ignore = tests
 tar-ignore = .tox
-tar-ignore = tox.ini
\ No newline at end of file
+tar-ignore = tox.ini
+tar-ignore = .mypy_cache
+tar-ignore = .remarkrc.yml
+tar-ignore = .remarkrc_master.ym
```
Comment (PawelLipski) [inline debian/source/options]:
```suggestion
tar-ignore = .remarkrc_master.yml
```
plus keep abc order ;)

File: debian/source/options [hunk 10]
```diff
@@ -31,4 +31,8 @@ tar-ignore = .stestr.conf
...
+tar-ignore = .dockerignore
```
Comment (PawelLipski) [inline debian/source/options]: Also, test-results!

```
+ tar tvf ../python3-git-machete_3.7.2~18.04.tar.gz
drwxrwxr-x 0/0               0 2022-02-10 14:20 git-machete/
-rw-r--r-- 0/0              31 2022-02-05 15:50 git-machete/.remarkrc_master.yml
-rw-r--r-- 0/0             126 2020-04-24 21:34 git-machete/MANIFEST.in
-rw-r--r-- 0/0            8652 2022-02-10 11:54 git-machete/README.md
drwxr-xr-x 0/0               0 2022-02-10 14:20 git-machete/debian/
-rw-r--r-- 0/0           13638 2022-02-10 14:20 git-machete/debian/changelog
-rw-r--r-- 0/0               3 2020-04-24 21:34 git-machete/debian/compat
-rw-r--r-- 0/0             425 2020-04-24 21:34 git-machete/debian/control
-rw-r--r-- 0/0            1075 2022-02-10 14:20 git-machete/debian/copyright
-rwxr-xr-x 0/0             125 2020-04-24 21:34 git-machete/debian/rules
drwxr-xr-x 0/0               0 2022-02-10 14:16 git-machete/debian/source/
-rw-r--r-- 0/0             861 2022-02-10 14:16 git-machete/debian/source/options
-rw-r--r-- 0/0             638 2021-11-25 13:48 git-machete/git-machete
drwxr-xr-x 0/0               0 2022-02-10 14:20 git-machete/git_machete/
-rw-r--r-- 0/0              22 2022-02-09 17:04 git-machete/git_machete/__init__.py
-rw-r--r-- 0/0           37136 2022-02-09 17:04 git-machete/git_machete/cli.py
-rw-r--r-- 0/0          123588 2022-02-09 17:04 git-machete/git_machete/client.py
-rw-r--r-- 0/0            1017 2022-02-02 19:47 git-machete/git_machete/constants.py
-rw-r--r-- 0/0           50348 2022-02-09 17:04 git-machete/git_machete/docs.py
-rw-r--r-- 0/0             855 2021-11-25 13:49 git-machete/git_machete/exceptions.py
-rw-r--r-- 0/0           49601 2022-02-07 18:08 git-machete/git_machete/git_operations.py
-rw-r--r-- 0/0           11646 2021-11-27 23:41 git-machete/git_machete/github.py
-rw-r--r-- 0/0            2865 2021-11-25 13:48 git-machete/git_machete/options.py
-rw-r--r-- 0/0            8696 2022-02-02 19:47 git-machete/git_machete/utils.py
-rw-r--r-- 0/0             193 2022-02-07 18:08 git-machete/requirements.txt
-rw-r--r-- 0/0            1255 2021-10-08 08:28 git-machete/setup.py
drwxr-xr-x 0/0               0 2022-02-10 09:33 git-machete/test-results/
-rw-r--r-- 0/0            6115 2022-02-10 09:33 git-machete/test-results/py38.xml
```

**Review by PawelLipski — APPROVED** [review]
image
