### PR TITLE
Issue #665: Fix update to homebrew

### LINKED ISSUE #665: Once git-machete is available in homebrew-core, replace the current code for updating the tap
- [x] Let's use `brew bump-formula-pr`, as suggested in https://github.com/Homebrew/homebrew-core/pull/111891#issuecomment-1261109350 instead. Worth checking what the linked Github Action does (even though we're not gonna use it, as we run on CircleCI).
- [x] README.md for installation via Homebrew
- [x] CONTRIBUTING.md about post-release steps
- [x] RELEASE_NOTES.md to mention the availability of the package via homebrew-core (as opposed to a tap)
- [x] Archive (**not** delete) [VirtusLab/homebrew-git-machete](https://github.com/VirtusLab/homebrew-git-machete) repo

### PR DESCRIPTION
**Pull request by amalota**

### CODE REVIEW

File: ci/homebrew/ci-deploy.sh [hunk 1]
```diff
@@ -11,14 +14,22 @@ else
...
 if [[ $do_push == true ]]; then
-  brew brew bump-formula-pr --url $url --sha256 $sha256 git-machete
+  brew bump-formula-pr --url "$url" --sha256 "$sha256" git-machete
 else
   echo "Refraining from push since it's a dry run"
-  brew bump-formula-pr --dry-run --url $url --sha256 $sha256 git-machete
+  brew bump-formula-pr --write-only --url "$url" --sha256 "$sha256" git-machete
+fi
+
+brew install --build-from-source --formula /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git-machete.rb
```
Comment (PawelLipski) [inline ci/homebrew/ci-deploy.sh:29]: Wow so homebrew-core is itself considered a _tap_... I always thought taps are only the custom repos like `VirtusLab/homebrew-git-machete` of ours 😯

**Review by PawelLipski — APPROVED** [review]
