### PR TITLE
Issue #554: `ZeroDivisionError` during snapping of `git machete`

### LINKED ISSUE #554: `ZeroDivisionError` in `Publish snap to the stable channel` 😯
https://app.circleci.com/pipelines/github/VirtusLab/git-machete/2140/workflows/e0387021-59c2-4e57-b572-d8af5b6c4487/jobs/10054
```
+ snapcraftctl prime
The interpreter 'python3' for 'bin/git-machete' was resolved to 'usr/bin/python3'.
The command 'bin/git-machete' has been changed to 'usr/bin/python3 $SNAP/bin/git-machete' to safely account for the interpreter.
Snapping |                                                           Snapping /                                                           Snapping -                                                           Snapping \                                                           Snapping |                                                           Snapping /                                                           Snapping -                                                           Snapping \                                                           Snapping |                                                           Snapping /                                                           Snapping -                                                           Snapping \                                                           Snapping |                                                           Snapping /                                                           Snapping -                                                           Snapping \                                                           Snapping |                                                           Snapping /                                                           Snapping |                                                           
Snapped git-machete_3.11.0_multi.snap
Traceback (most recent call last):
  File "/snap/snapcraft/7710/bin/snapcraft", line 8, in <module>
    sys.exit(run())
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/snapcraft/cli.py", line 181, in run
    dispatcher.run()
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/dispatcher.py", line 406, in run
    return self._loaded_command.run(self._parsed_command_args)
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/snapcraft/commands/account.py", line 108, in run
    emit.message(
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/messages.py", line 621, in func
    return wrapped_func(self, *args, **kwargs)
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/messages.py", line 725, in message
    self._printer.show(sys.stdout, text, use_timestamp=use_timestamp)  # type: ignore
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/messages.py", line 374, in show
    self._show(msg)
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/messages.py", line 334, in _show
    self._write_line(msg)
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/messages.py", line 279, in _write_line
    cleaner = " " * (usable - len(text) % width)
ZeroDivisionError: integer division or modulo by zero
```

### PR DESCRIPTION
**Pull request by amalota**

### CODE REVIEW

File: ci/snap/ci-deploy.sh [hunk 1]
```diff
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
 
-set -e -o pipefail -u
+set -e -o pipefail -u -x
+
+stty size
```
Comment (PawelLipski) [inline ci/snap/ci-deploy.sh]: Okay... so the value of `width` is ultimately extracted by `snapcraftctl` from `stty`? 🤔

Comment (PawelLipski) [reply ci/snap/ci-deploy.sh]: No way to make `snapcraft` **dis**interested in terminal completely? Like idk, piping the output through `| cat`

File: RELEASE_NOTES.md [hunk 2]
```diff
@@ -1,5 +1,7 @@
 # Release notes
 
+## New in git-machete 3.11.1
+
```
Comment (PawelLipski) [inline RELEASE_NOTES.md:4]: Pls fill up, just `fixed: release to Snap Store` or sth

File: ci/snap/ci-deploy.sh [hunk 3]
```diff
@@ -2,6 +2,7 @@
 
 set -e -o pipefail -u
 
+export COLUMNS=1
```
Comment (PawelLipski) [inline ci/snap/ci-deploy.sh:9]: Pls add a comment, esp. a reference to the place in snapcraft CLI code where this env var is retrieved, plus reference to your issue

**Review by PawelLipski — APPROVED** [review]
