### PR TITLE
Issue #615: Update branch annotations after `github retarget-pr`

### LINKED ISSUE #615: `github retarget-pr` should update annotation for the branch
I've got sth like

```
 main
  │
  └─FOO-138  PR #32
    │
    └─refactor/FOO-131-subnet-typo  PR #33 WRONG PR BASE or MACHETE PARENT? PR has 'main'
```

Then I've run `git machete github retarget-pr` while on `refactor/FOO-131-subnet-typo`:

```
$ git machete github retarget-pr 
The base branch of PR #33 has been switched to FOO-138
```

But the annotation hasn't changed... would be good if it was overwritten on retarget, just as with `create-pr`

### PR DESCRIPTION
**Pull request by amalota**

### CODE REVIEW

File: ci/checks/prohibit-strings-split-without-delimiter.sh [hunk 1]
```diff
@@ -5,5 +5,5 @@ set -e -o pipefail -u
 self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
 self_name=$(basename --suffix=.sh "$0")
 
-git ls-files '*.py' ':!**/tests/**' \
+git ls-files '*.py' ':!tests/**' \
```
Comment (amalota) [inline ci/checks/prohibit-strings-split-without-delimiter.sh:8]: Bug -> this actually didn't exclude tests dir

**Review by PawelLipski — APPROVED** [review]
:benissimo:
